/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 02 09:15:26 GMT 2026
 */

package com.examples.with.different.packagename.rmi.testlistener;

import org.junit.Test;
import static org.junit.Assert.*;
import com.examples.with.different.packagename.rmi.testlistener.SampleTargetProgram;

public class SampleTargetProgram_SampleTest {

	  @Test(timeout = 4000)
	  public void test04()  throws Throwable  {
		  int int0 = 1578;
		  int int1 = 1234;
	      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
	      int1 = 1235;
	      int int2 = sampleTargetProgram0.sum(int0, int1);
	  }


  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum1(1, (-1173));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = null;
      try {
        sampleTargetProgram0 = new SampleTargetProgram(false);
      } catch(RuntimeException e) {
         //
         // contruction is invalid
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum1(694, 694);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum1(2, (-486));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      // Undeclared exception!
      try { 
        sampleTargetProgram0.sum((-584), (-584));
      } catch(RuntimeException e) {
         //
         // check failed
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum(2115, 3711);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.other(1388, 2);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.other((-4481), (-4481));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      // Undeclared exception!
      try { 
        sampleTargetProgram0.other((-10000), (-10000));
      } catch(RuntimeException e) {
         //
         // check failed
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      // Undeclared exception!
      try { 
        sampleTargetProgram0.sum(4885, 7102);
      } catch(RuntimeException e) {
         //
         // check failed
         //
      }
  }
}
