/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 05 16:19:23 GMT 2026
 */

package com.examples.with.different.packagename.rmi.testlistener;

import org.junit.Test;
import static org.junit.Assert.*;
import com.examples.with.different.packagename.rmi.testlistener.SampleTargetProgram;

public class SampleTargetProgram_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum1(1, (-96));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = null;
      try {
        sampleTargetProgram0 = new SampleTargetProgram(false);
      } catch(RuntimeException e) {
         //
         // contruction is invalid
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum1(665, 19);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum1(2, (-486));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum(2812, 0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      // Undeclared exception!
      try { 
        sampleTargetProgram0.sum((-244), (-244));
      } catch(RuntimeException e) {
         //
         // check failed
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum((-1), 0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.sum(577, 0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.other(0, 0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      int int0 = sampleTargetProgram0.other((-1), (-1));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      // Undeclared exception!
      try { 
        sampleTargetProgram0.other((-10000), (-10000));
      } catch(RuntimeException e) {
         //
         // check failed
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SampleTargetProgram sampleTargetProgram0 = new SampleTargetProgram(true);
      // Undeclared exception!
      try { 
        sampleTargetProgram0.other(5368, 5368);
      } catch(RuntimeException e) {
         //
         // check failed
         //
      }
  }
}
